# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build nativeImage
    - name: Rename exe
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      run: mv app/build/graal/video_presenter app/build/graal/video_presenter-${{ matrix.os }}
    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: video-presenter-${{ matrix.os }}
        path: |
          app/build/graal/*
          
  release:
    name: release
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Builds
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Publish release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            video-presenter-macos-latest/*
            video-presenter-ubuntu-latest/*
            video-presenter-windows-latest/*
